steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sodium-airport-395522/my-service', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'my-service', '--image', 'gcr.io/sodium-airport-395522/my-service', '--region', 'us-west2', '--platform', 'managed']
